project:
  type: website

website:
  title: "NBA Scorigami"
  navbar:
    left:
      - href: basketball.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: none
    toc: true